- doc/Usage.txt
- src/gwhisper/gwhisper.cpp
- src/libArgParse/Alternation.hpp
- src/libArgParse/GrammarInjector.hpp
- src/libCli/CMakeLists.txt
- src/libCli/Call.cpp
- src/libCli/GrammarConstruction.cpp
- src/libCli/cliUtils.cpp
- src/libCli/cliUtils.hpp
Signed-off-by: Rainer Schoenberger <rschoe@de.ibm.com>
> [#25] Add channel connection state check with timeout

- .travis.yml
> ci: narrowing down cppcheck results

- .travis.yml
- src/libArgParse/GrammarFactory.hpp
- src/libArgParse/GrammarInjector.hpp
- src/libCli/GrammarConstruction.cpp
... and fixed low hanging fruit of the findings
> [#37] updated cppcheck suppression list 

- src/libCli/Call.cpp
- src/libCli/GrammarConstruction.cpp
- src/libCli/OutputFormatting.cpp
- src/libCli/OutputFormatting.hpp
> [#35] Custom output formatter supports different modifiers (bin/hex/dec)

- .travis.yml
- travis/cppcheck_suppressions.txt
> cppcheck: suppress remaining false positives

- src/libCli/OutputFormatting.cpp
- src/libCli/OutputFormatting.hpp
add the feature for #12 
fixed #30
> [#12] [#30] using shorter representation for protobuf map in output and sorted by key

- src/libCli/Call.cpp
- src/libCli/Call.hpp
- src/libCli/ConnectionManager.hpp
- src/libCli/GrammarConstruction.cpp
using singleton pattern to manage and re-use the connection informantion for #51
> [#51] imporve the RPCs performence for each call

- CMakeLists.txt
- README.md
- complete.fish
- doc/Usage.txt
- src/gwhisper/gwhisper.cpp
- src/libCli/Completion.cpp
- src/libCli/Completion.hpp
- src/libCli/GrammarConstruction.cpp
This is not totally ready for merge into master yet.
I created a pull-request to receive feedback from reviewers, as well as to encourage testers to find bugs.
> [#45] Implement support for fish shell

- .travis.yml
> [#69] disable broken cppcheck

- .travis.yml
> [#69] disable installing cppcheck snap

- src/libCli/GrammarConstruction.cpp
- src/libCli/MessageParsing.cpp
- tests/functionTests/completionTests.txt
add try...catch block to fix the exception thrown from stol().
> bug fix stol() exception on conversion #56

- CMakeLists.txt
#49
Signed-off-by: taojun <taojun.li@ibm.com>
> avoid to compile again when make install for #49

- README.md
using dnf
Signed-off-by: taojun <taojun.li@ibm.com>
> prerequisites' installation via fedora dnf

- src/libArgParse/EscapedString.hpp
- src/libCli/CMakeLists.txt
- tests/functionTests/rpcExecutionTests.txt
try to fix bug #86 
Signed-off-by: taojun <taojun.li@ibm.com>
> bugfix #86: fix missing last charactor of string in repeated field.

- build.sh
- src/libCli/GrammarConstruction.cpp
- tests/functionTests/completionTests.txt
Fixes #53
Signed-off-by: Rainer Schoenberger <rschoe@de.ibm.com>
> Support recursive datastructures up to depth of 10

- build.sh
- src/libArgParse/Alternation.hpp
- src/libArgParse/Concatenation.hpp
- src/libArgParse/Optional.hpp
- src/libCli/Call.cpp
- src/libCli/GrammarConstruction.cpp
- src/libCli/GrammarConstruction.hpp
- tests/functionTests/completionTests.txt
- tests/unitTests/AlternationTest.cpp
- tests/unitTests/ConcatenationTest.cpp
- tests/unitTests/GrammarComboTests.cpp
- tests/unitTests/OptionalTest.cpp
Implementation for #90
ready for testing. completion does not work 100%
> Allow unix domain sockets #90

- src/libCli/Completion.cpp
- tests/functionTests/CMakeLists.txt
- tests/functionTests/completionTests_fish.txt
Signed-off-by: Anna Riesch <Anna.Riesch@ibm.com>
> Test for fish and modifications for whitespace-handling in completion

- doc/Usage.txt
- src/libCli/GrammarConstruction.cpp
- tests/functionTests/rpcExecutionTests.txt
- tests/functionTests/runFunctionTest.sh
- tests/testServer/ServiceStreamingRpcs.cpp
- tests/testServer/ServiceStreamingRpcs.hpp
- tests/testServer/examples.proto
> Fix String escaping: Change escape character from : to % and fix functional tests

- src/libCli/Completion.cpp
Fixes #108 :  Adapted trim check
> Fixed Doc Issue

- build.sh
- cmake/gRPC.cmake
- src/libCli/CMakeLists.txt
- src/libCli/GrammarConstruction.cpp
- tests/testServer/testServer.cpp
> fix health check service causing crash

- doc/Usage.txt
Signed-off-by: Anna Riesch <Anna.Riesch@ibm.com>
> Adapted documentation

- src/version/generateVersionDefine.sh
Signed-off-by: Anna Riesch <Anna.Riesch@ibm.com>
> Prepare v4.0.1.

- CMakeLists.txt
- README.md
Signed-off-by: Rainer Schoenberger <rschoe@de.ibm.com>
> make building grpc default cmake behavior
